trigger: none

pool: infy agent

variables: 
  palakpanner: '$(System.DefaultWorkingDirectory)/Environment'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $palakpanner
    backendServiceArm: 'infy practice'
    backendAzureRmResourceGroupName: 'agnitypartners'
    backendAzureRmStorageAccountName: 'agnity'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'agnity.tfstate'
